DELETE  
-- select * 
-- FROM _TREE WHERE 
-- NOT 
FROM _FORM WHERE NOT
(
 PARAGRAF LIKE 'sys%' OR PARAGRAF='1.00' OR PARAGRAF='1.'
 OR PARAGRAF LIKE '2%' 
 OR PARAGRAF LIKE '3%' 
 OR PARAGRAF LIKE '5%' 
 OR PARAGRAF = '6'
 OR PARAGRAF LIKE '6.1%' 
 
)